services:
  - type: web
    name: pons-meat-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist/meat-website
    envVars:
      - key: NODE_ENV
        value: production 